name: Access CTF Site

on:
  push:
    branches:
      - main  # Trigger this workflow when pushing to the main branch

jobs:
  request_flag:
    runs-on: ubuntu-latest  # Using a GitHub hosted runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out the repository if needed

    - name: Make GET request to CTF site with proper headers
      run: |
        response=$(curl -s -H "Content-Type: application/json" -H "X-CERTUNLP: flag" https://actions.ctf.cert.unlp.edu.ar/)
        echo "Response: $response"
